import assert from 'node:assert/strict';
import fs from 'node:fs';

const main = fs.readFileSync('main.js', 'utf8');
const workflow = fs.readFileSync('src/agent/easyApply/workflow.ts', 'utf8');
const navigator = fs.readFileSync('src/agent/stateMachine/stepNavigator.ts', 'utf8');
const browser = fs.readFileSync('AgentBrowser/AgentBrowser.tsx', 'utf8');
const browserSession = fs.readFileSync('AgentBrowser/browserSession.ts', 'utf8');
const browserFeatures = fs.readFileSync('AgentBrowser/electron-browser-features.js', 'utf8');
const webviewPreload = fs.readFileSync('AgentBrowser/preload-webview.cjs', 'utf8');
const appPreload = fs.readFileSync('preload-popup.cjs', 'utf8');
const autoApply = fs.readFileSync('src/agent/autoApply/autoApplyEngine.ts', 'utf8');
const releaseWorkflow = fs.readFileSync('.github/workflows/release.yml', 'utf8');
const installer = fs.readFileSync('scripts/zeroapply.iss', 'utf8');

assert.match(main, /setPermissionRequestHandler/);
assert.match(main, /Website permission/);
assert.match(main, /Allow for this session/);
assert.match(main, /defaultId: 1/);
assert.match(main, /requireTrustedIpcSender\(event\)/);
assert.match(main, /webPreferences\.preload = PRELOAD_WEBVIEW_PATH/);
assert.match(main, /partition: AUTH_PARTITION/);
for (const portal of ['linkedin.com', 'indeed.com', 'glassdoor.com', 'naukri.com', 'unstop.com']) {
  assert.match(main, new RegExp(`'${portal.replace('.', '\\.')}('|,)`));
}
assert.match(navigator, /action === 'submit' && !allowSubmit/);
assert.match(workflow, /const confirmed = await checkSubmissionConfirmed/);
assert.doesNotMatch(browser, /console-message/);
assert.doesNotMatch(autoApply, /includes\(expectedHost\)/);
assert.match(autoApply, /hostname === expectedHost \|\| hostname\.endsWith/);
assert.match(main, /did-create-window/);
assert.match(main, /isDeferredPopupUrl/);
assert.match(main, /isLinkedInTrackerUrl/);
assert.match(main, /show: false/);
assert.match(main, /childWindow\.webContents\.on\('will-redirect', routeChildNavigation\)/);
assert.match(main, /20_000/);
assert.match(main, /function sendOpenTab/);
assert.match(main, /mainWindow\.webContents\.send\('zeroapply-open-tab'/);
assert.match(main, /resolvePopupDestination/);
assert.match(main, /LinkedIn did not provide a usable destination/);
assert.match(main, /consumePopupGesture/);
assert.match(main, /BACKGROUND_POPUP_HOSTS = \['cs\.ns1p\.net'\]/);
assert.match(webviewPreload, /ipcRenderer\.sendToHost\('zeroapply-telemetry'/);
assert.match(webviewPreload, /zeroapply-webview-popup-gesture/);
assert.match(webviewPreload, /linkCandidatesFromEvent/);
assert.match(webviewPreload, /executeJavaScriptInIsolatedWorld\(0/);
assert.match(webviewPreload, /zeroapply-webview-window-open/);
assert.match(main, /ipcMain\.on\('zeroapply-webview-window-open'/);
assert.match(main, /zeroapply-linkedin-apply-click/);
assert.doesNotMatch(webviewPreload, /preventDefault|stopImmediatePropagation/);
assert.doesNotMatch(webviewPreload, /navigator\.webdriver|window\.chrome|navigator\.permissions\.query/);
assert.doesNotMatch(main, /requestHeaders\['sec-ch-ua/);
assert.match(main, /migrateBrowserCacheIfNeeded/);
assert.match(main, /\.clearCache\(\)/);
assert.doesNotMatch(main, /clearStorageData/);
const popupHandler = main.slice(main.indexOf('const handleWindowOpen'), main.indexOf('function compareVersions'));
assert.match(popupHandler, /sendOpenTab\(parsed\.toString\(\), sourceContents\)/);
assert.doesNotMatch(main, /\.sendToHost\(/);
assert.match(browserSession, /MAX_BROWSER_TABS = 20/);
assert.match(browser, /role="tablist"/);
assert.match(browser, /partition="persist:zeroapply_auth"/);
assert.match(browser, /src=\{initialUrl\.current\}/);
assert.doesNotMatch(browser, /src=\{tab\.url\}/);
assert.doesNotMatch(browser, /view\.loadURL/);
assert.match(browser, /did-fail-load/);
assert.match(browser, /render-process-gone/);
assert.match(browser, /addEventListener\('dom-ready', handleDomReady\)/);
assert.doesNotMatch(browser, /\n\s*onReady\(tab\.id, view\);\n\s*view\.addEventListener\('dom-ready'/);
assert.match(browser, /Retry page/);
assert.match(main, /targetSession\.on\('will-download'/);
assert.match(main, /dialog\.showSaveDialog/);
assert.match(main, /item\.pause\(\)/);
assert.match(appPreload, /zeroapply-browser-event/);
assert.match(appPreload, /zeroapply-browser-command/);
assert.match(main, /before-input-event/);
assert.match(main, /context-menu/);
assert.match(main, /savePage/);
assert.match(browserFeatures, /mailto:/);
assert.match(main, /rendererLoadAttempts > 3/);
assert.match(main, /webviewRecoveryState/);
assert.match(main, /process\.on\('unhandledRejection'/);
assert.match(main, /process\.on\('uncaughtException'/);
assert.match(main, /api\.github\.com\/repos\/saiprasadchary-hub\/zeroapply\/releases\/latest/);
assert.match(main, /releaseUrl\.startsWith\(RELEASES_URL_PREFIX\)/);
assert.match(releaseWorkflow, /contents: write/);
assert.match(releaseWorkflow, /gh release (create|upload)/);
assert.match(installer, /AppUpdatesURL=https:\/\/github\.com\/saiprasadchary-hub\/zeroapply\/releases\/latest/);

console.log('security policy tests passed');
